Support Boost 1.84 (#1)
* Update host cmakelists to support compilation with gcc 11, python 3 and boost 1.84

* Fix removed BOOST_BIG_ENDIAN

* Fix changed namesapce of_X placeholders

* Fix missing <thread> include to use sleep_for

* Fix noncopyable missing include

* Fix undefined boost::math

* Fix undefined reference to boost::math::sign

* Force boost 1.84

* Use UHD endiannes defintion from HEAD

* Fix partial commit

* Fix boost on windows

* Fix missing math constants on Windows

* Fix missing array include on Windows